"use client";

import { BedDouble, Pencil, Plus, Trash2, Truck, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select } from "@/components/ui/select";
import { Card, CardContent } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import type { InventoryAssetDTO, SupplierDTO } from "@/types";

export function InventoryAssetManager({ items, suppliers, kind }: { items: InventoryAssetDTO[]; suppliers: SupplierDTO[]; kind: "hotel" | "vehicle" }) {
  const label = kind === "hotel" ? "Hotel" : "Vehicle"; const Icon = kind === "hotel" ? BedDouble : Truck;
  const [editing, setEditing] = useState<InventoryAssetDTO | null | undefined>(undefined);
  return <div className="space-y-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-bold">{label}s</h2><p className="text-sm text-muted-foreground">Add multiple {label.toLowerCase()} records under each supplier.</p></div><Button variant="gradient" onClick={() => setEditing(null)}><Plus className="size-4" />Add {label}</Button></div>{items.length ? <Card><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="p-4">{label}</th><th className="p-4">Supplier</th><th className="p-4">Details</th><th className="p-4 text-right">Action</th></tr></thead><tbody>{items.map(item => <tr key={item._id} className="border-b"><td className="p-4"><div className="flex items-center gap-3">{item.image ? <img src={item.image} alt="" className="size-12 rounded-md object-cover" /> : <span className="flex size-12 items-center justify-center rounded-md bg-secondary"><Icon className="size-5 text-primary" /></span>}<p className="font-semibold">{item.name}</p></div></td><td className="p-4">{typeof item.supplier === "string" ? "—" : item.supplier.companyName}</td><td className="p-4"><p className="max-w-sm truncate">{item.description || "—"}</p><p className="mt-1 text-xs text-muted-foreground">{item.facilities.join(" · ") || "No facilities added"}</p></td><td className="p-4 text-right"><Button size="icon" variant="ghost" onClick={() => setEditing(item)}><Pencil className="size-4" /></Button></td></tr>)}</tbody></table></CardContent></Card> : <EmptyState icon={Icon} title={`No ${label.toLowerCase()}s added`} action={<Button variant="gradient" onClick={() => setEditing(null)}><Plus className="size-4" />Add {label}</Button>} />}{editing !== undefined ? <AssetDrawer asset={editing} suppliers={suppliers} kind={kind} onClose={() => setEditing(undefined)} /> : null}</div>;
}

function AssetDrawer({ asset, suppliers, kind, onClose }: { asset: InventoryAssetDTO | null; suppliers: SupplierDTO[]; kind: "hotel" | "vehicle"; onClose: () => void }) {
  const router = useRouter(); const [saving, setSaving] = useState(false); const supplierId = typeof asset?.supplier === "string" ? asset.supplier : asset?.supplier?._id ?? "";
  const [form, setForm] = useState({ supplier: supplierId, name: asset?.name ?? "", image: asset?.image ?? "", description: asset?.description ?? "", directHotelBooking: asset?.directHotelBooking ?? false, facilities: asset?.facilities.join("\n") ?? "" }); const label = kind === "hotel" ? "Hotel" : "Vehicle";
  const set = (key: keyof typeof form, value: string) => setForm(current => ({ ...current, [key]: value }));
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); try { const response = await fetch(asset ? `/api/admin/inventory-assets/${asset._id}` : "/api/admin/inventory-assets", { method: asset ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, kind, facilities: form.facilities.split("\n").map(item => item.trim()).filter(Boolean) }) }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.message || `Unable to save ${label.toLowerCase()}`); toast.success(`${label} saved`); router.refresh(); onClose(); } catch (error) { toast.error((error as Error).message); setSaving(false); } }
  return <div className="fixed inset-0 z-[80]"><button className="absolute inset-0 bg-black/45" onClick={onClose} aria-label="Close" /><aside className="absolute right-0 top-0 flex h-full w-full max-w-xl flex-col bg-background shadow-2xl"><div className="flex items-center justify-between border-b p-5"><h2 className="text-lg font-bold">{asset ? `Edit ${label}` : `Add ${label}`}</h2><Button size="icon" variant="ghost" onClick={onClose}><X /></Button></div><form onSubmit={submit} className="space-y-4 overflow-y-auto p-5"><div><Label>Supplier *</Label><Select required value={form.supplier} onChange={event => set("supplier", event.target.value)}><option value="">Select supplier</option>{suppliers.map(supplier => <option key={supplier._id} value={supplier._id}>{supplier.companyName}</option>)}</Select></div><div><Label>{label} name *</Label><Input required value={form.name} onChange={event => set("name", event.target.value)} /></div>{kind === "hotel" ? <><div><Label>Image URL</Label><Input type="url" value={form.image} onChange={event => set("image", event.target.value)} /></div><div><Label>Description</Label><Textarea value={form.description} onChange={event => set("description", event.target.value)} /></div><label className="flex cursor-pointer items-center justify-between gap-4 rounded-xl border border-border bg-secondary/20 p-4"><span><span className="block font-semibold">Publicly visible for direct booking</span><span className="mt-1 block text-sm text-muted-foreground">Show this hotel on the Voibee Hotels page.</span></span><input type="checkbox" checked={form.directHotelBooking} onChange={event => setForm(current => ({ ...current, directHotelBooking: event.target.checked }))} className="size-5 shrink-0 accent-primary" /></label><div><Label>Facilities (one per line)</Label><Textarea value={form.facilities} onChange={event => set("facilities", event.target.value)} placeholder={"Swimming pool\nBreakfast\nWi-Fi"} /></div></> : <div><Label>Vehicle details</Label><Textarea value={form.description} onChange={event => set("description", event.target.value)} placeholder="Model, capacity, AC, registration details" /></div>}<div className="flex justify-end gap-2 pt-3"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit" variant="gradient" disabled={saving}>{saving ? "Saving…" : "Save"}</Button></div></form></aside></div>;
}
